server:
  shutdown: graceful
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zeroorder?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: zerobase
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Mysql8Dialect
  redis:
    host: localhost
    port: 6379

feign:
  client:
    url:
      user-api: localhost:8081
  okhttp:
    enabled: true
  autoconfiguration:
    jackson:
      enabled: true
