### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc5OTc5NDEzLCJleHAiOjE2ODAwNjU4MTN9.927I0wY3MXI1wYh4WXUdpIDN6vTRjBFAL9JLP1KwQn0

{
  "description": "cap",
  "items": [
    {
      "count": 5,
      "name": "cap1",
      "price": 7000
    }
  ],
  "name": "Adidas"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc5OTc5NDEzLCJleHAiOjE2ODAwNjU4MTN9.927I0wY3MXI1wYh4WXUdpIDN6vTRjBFAL9JLP1KwQn0

{
  "productId": 2,
  "count": 5,
  "name": "cap3",
  "price": 4000
}

### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc5ODgyODU5LCJleHAiOjE2Nzk5NjkyNTl9.ow85cwUTko1FS5w18qNMwmZPAaWO0H1tf1aeePj286s

{
  "id": 1,
  "name": "adidos",
  "description": "string",
  "items": [
    {
      "id": 1,
      "name": "딈",
      "price": 5000,
      "count": 1
    }
  ]
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc5ODgyODU5LCJleHAiOjE2Nzk5NjkyNTl9.ow85cwUTko1FS5w18qNMwmZPAaWO0H1tf1aeePj286s

{
  "id": 1,
  "name": "뇌이키",
  "price": 6000,
  "count": 1
}

### 상품 삭제
DELETE http://localhost:8082/seller/product?id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc5ODgyODU5LCJleHAiOjE2Nzk5NjkyNTl9.ow85cwUTko1FS5w18qNMwmZPAaWO0H1tf1aeePj286s


### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc5ODgyODU5LCJleHAiOjE2Nzk5NjkyNTl9.ow85cwUTko1FS5w18qNMwmZPAaWO0H1tf1aeePj286s

### 상품 검색
GET http://localhost:8082/search/product?name=Nike
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc5ODgyODU5LCJleHAiOjE2Nzk5NjkyNTl9.ow85cwUTko1FS5w18qNMwmZPAaWO0H1tf1aeePj286s

### 상품 상세 조회
GET http://localhost:8082/search/product/detail?productId=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc5ODgyODU5LCJleHAiOjE2Nzk5NjkyNTl9.ow85cwUTko1FS5w18qNMwmZPAaWO0H1tf1aeePj286s

### 카트 추가
POST http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2Nzk5ODQ0ODMsImV4cCI6MTY4MDA3MDg4M30.NQaIJupZAkj0nnRj-KP9FdxvogbULW0GA_R7cUyV17s

{
  "description": "cap",
  "id": 2,
  "items": [
    {
      "count": 5,
      "id": 3,
      "name": "cap1",
      "price": 7000
    }
  ],
  "name": "Adidas",
  "sellerId": 1
}

### 카트 조회
GET http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2Nzk5ODQ0ODMsImV4cCI6MTY4MDA3MDg4M30.NQaIJupZAkj0nnRj-KP9FdxvogbULW0GA_R7cUyV17s

### 카트 업데이트
PUT http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2Nzk5ODQ0ODMsImV4cCI6MTY4MDA3MDg4M30.NQaIJupZAkj0nnRj-KP9FdxvogbULW0GA_R7cUyV17s

{
  "customerId": 2,
  "messages": [],
  "products": [
    {
      "description": "cap",
      "id": 2,
      "items": [
        {
          "count": 1,
          "id": 4,
          "name": "cap3",
          "price": 4000
        }
      ],
      "name": "Adidas",
      "sellerId": 2
    }
  ]
}

### 카트 주문
POST http://localhost:8082/customer/cart/order
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5NXEvaEs1bkwxbUdtVzZocnk2WFByQXphUVBGVHFES2dGRmhrcDdwb1owPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2Nzk5ODQ0ODMsImV4cCI6MTY4MDA3MDg4M30.NQaIJupZAkj0nnRj-KP9FdxvogbULW0GA_R7cUyV17s

{
  "customerId": 2,
  "messages": [],
  "products": [
    {
      "description": "cap",
      "id": 2,
      "items": [
        {
          "count": 1,
          "id": 4,
          "name": "cap3",
          "price": 4000
        }
      ],
      "name": "Adidas",
      "sellerId": 2
    }
  ]
}